"""empty message

Revision ID: 4c5e1fec4c85
Revises: 
Create Date: 2018-09-03 16:12:27.966000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4c5e1fec4c85'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('card', 'card_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.alter_column('item_has', 'stat_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_index('belongs_to', table_name='pet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('belongs_to', 'pet', ['belongs_to'], unique=False)
    op.alter_column('item_has', 'stat_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.alter_column('card', 'card_name',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    # ### end Alembic commands ###
