"""empty message

Revision ID: 4ed06178afd5
Revises: 
Create Date: 2018-09-02 21:43:50.527000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ed06178afd5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('name', sa.String(length=50), nullable=True))
    op.add_column('card', sa.Column('text', sa.String(length=10000), nullable=True))
    op.add_column('card', sa.Column('type', sa.String(length=50), nullable=True))
    op.drop_column('card', 'card_type')
    op.drop_column('card', 'card_name')
    op.drop_column('card', 'trial452')
    op.drop_column('card', 'card_text')
    op.drop_constraint(u'champion_ibfk_1', 'champion', type_='foreignkey')
    op.create_foreign_key(None, 'champion', 'card', ['card_id'], ['card_id'])
    op.drop_column('champion', 'trial455')
    op.drop_constraint(u'item_ibfk_1', 'item', type_='foreignkey')
    op.create_foreign_key(None, 'item', 'card', ['card_id'], ['card_id'])
    op.drop_column('item', 'trial455')
    op.alter_column('item_has', 'stat_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=True)
    op.drop_constraint(u'item_has_ibfk_1', 'item_has', type_='foreignkey')
    op.create_foreign_key(None, 'item_has', 'item', ['card_id'], ['card_id'])
    op.drop_column('item_has', 'trial455')
    op.drop_constraint(u'neutral_monster_ibfk_1', 'neutral_monster', type_='foreignkey')
    op.create_foreign_key(None, 'neutral_monster', 'card', ['card_id'], ['card_id'])
    op.drop_column('neutral_monster', 'trial455')
    op.drop_index('idx_belongs_to', table_name='pet')
    op.drop_constraint(u'pet_ibfk_1', 'pet', type_='foreignkey')
    op.drop_constraint(u'pet_ibfk_2', 'pet', type_='foreignkey')
    op.create_foreign_key(None, 'pet', 'card', ['card_id'], ['card_id'])
    op.create_foreign_key(None, 'pet', 'champion', ['belongs_to'], ['card_id'])
    op.drop_column('pet', 'trial455')
    op.drop_constraint(u'summoner_spell_ibfk_1', 'summoner_spell', type_='foreignkey')
    op.create_foreign_key(None, 'summoner_spell', 'card', ['card_id'], ['card_id'])
    op.drop_column('summoner_spell', 'trial455')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('summoner_spell', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'summoner_spell', type_='foreignkey')
    op.create_foreign_key(u'summoner_spell_ibfk_1', 'summoner_spell', 'card', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.add_column('pet', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.drop_constraint(None, 'pet', type_='foreignkey')
    op.create_foreign_key(u'pet_ibfk_2', 'pet', 'champion', ['belongs_to'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_foreign_key(u'pet_ibfk_1', 'pet', 'card', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.create_index('idx_belongs_to', 'pet', ['belongs_to'], unique=False)
    op.add_column('neutral_monster', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'neutral_monster', type_='foreignkey')
    op.create_foreign_key(u'neutral_monster_ibfk_1', 'neutral_monster', 'card', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.add_column('item_has', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item_has', type_='foreignkey')
    op.create_foreign_key(u'item_has_ibfk_1', 'item_has', 'item', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.alter_column('item_has', 'stat_name',
               existing_type=sa.VARCHAR(length=20),
               nullable=False)
    op.add_column('item', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'item', type_='foreignkey')
    op.create_foreign_key(u'item_ibfk_1', 'item', 'card', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.add_column('champion', sa.Column('trial455', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'champion', type_='foreignkey')
    op.create_foreign_key(u'champion_ibfk_1', 'champion', 'card', ['card_id'], ['card_id'], onupdate=u'CASCADE', ondelete=u'CASCADE')
    op.add_column('card', sa.Column('card_text', sa.VARCHAR(length=10000), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('trial452', sa.CHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('card', sa.Column('card_name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.add_column('card', sa.Column('card_type', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.drop_column('card', 'type')
    op.drop_column('card', 'text')
    op.drop_column('card', 'name')
    # ### end Alembic commands ###
